/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PP11.Cab.Invoice.Generator;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
